# conda install mamba --yes -n base -c conda-forge
# mamba env create -f environment.yml
name: pacasam
channels:
  - conda-forge
  - plotly
dependencies:
  - python==3.9.*
  - pip
  - jupyterlab>=3 # better jupyter notebooks
  - numpy
  # --------- BDs & Geo --------- #
  - sqlalchemy==2.0.4
  - psycopg2
  - shapely
  - geoalchemy2
  - s3fs
  - geopandas
  - plotly
  - jupyter-dash 
  - ipywidgets>=7.6
  - python-kaleido
  # --------- linters --------- #
  - pre-commit # hooks for applying linters on commit
  - black # code formatting
  - isort # import sorting
  - flake8 # code analysis
  - pip:
    - black[jupyter]
    - hdbscan