# conda install mamba --yes -n base -c conda-forge
# mamba env create -f environment.yml
name: pacasam
channels:
  - conda-forge
  - plotly
dependencies:
  - python==3.9.*
  - pip
  - jupyterlab>=3 # better jupyter notebooks
  - numpy
  # --------- BDs & Geo --------- #
  - sqlalchemy==2.0.4
  - psycopg2
  - shapely
  - geoalchemy2
  - geopandas
  - plotly
  - ipywidgets>=7.6
  - python-kaleido  # to export plotly figures
  # - black[jupyter] # formatting
  # - black # code formatting
  - black-jupyter  # code formatting
  - tqdm # pretty progress bars
  - smbprotocol=1.10.*  # to read file in a Samba store - see. https://pypi.org/project/smbprotocol/
  # --------- linters --------- #
  - pre-commit # hooks for applying linters on commit
  - isort # import sorting
  - flake8 # code analysis
  # --------- tests ----------- #
  - pytest
  - pytest-cov
  - pytest-timeout  
  - pytest-xdist  # tests parallelization using `pytest -n NUM_CPUs`
  # --------- dependencies for ign-pdal-tools - they currently need explicit installation  ----------- #
  - conda-forge:pdal==2.5.*
  - conda-forge:python-pdal==3.2.*
  - requests
  - gdal
  - pip:
    # -   
    - hdbscan  # For OutliersSampler
    - laspy[lazrs,laszip]==2.1.*  # laspy with LAZ backend support
    - ign-pdal-tools  # for colorization of LAZ files
    # - tqdm  