# Configuration pour l'optimisation de l'échantillonnage de patches.

# Objectif de taille du dataset final.
target_total_num_patches: 10000  # 250km² = 100000 samples, 5000 samples -> 20x reduction  | Alternatively 75km² = 30000 samples.
frac_validation_set:  0.1 # float,ou "null" pour que la colonne "split" prenne la valeur "test" partout.


# kwargs for lipac database
connector_kwargs:
  # TODO: traiter ces éléments au même titre que id et mdp.
  db_lipac_host: "lidar-ia-vm3"
  db_lipac_name: "lidar_patch_catalogue"
  # extraction_sql_query_path -> croisement unique des tables de Lipac. Accès aux informations nécessaires.
  # Création a la volée des indicateurs booléens nécessaires à TargettedSampler.
  # Quatre variables sont requises pour procéder à l'échantillonnage, qui sont des variables
  # du module pacasam.connector.connector.

  # Nota: chemin vers requête SQL.
  extraction_sql_query_path: "configs/Lipac_query_enriched_targetted.sql"
  # Filtre sur la colonne "test" de Lipac. Choix: train, test, ou any (pour tout garder). 
  split: "test"
  # Lecture par parties de la base PostGIS.
  max_chunksize_for_postgis_extraction: 100000

DiversitySampler:
  # Gestion par parties (chunk) des vignettes via FPS.
  # Les vignettes sont ordonnées par leur identifiant unique "patch_id", et l'id est supposé avoir été choisi incrémentalement
  # à mesure que la base LiPaC est peuplée. D'où un notion de diversité qui va être également spatialisée.
  max_chunk_size_for_fps: 20000
  # "standardization" or "quantilization"
  # n_quantiles is only used if normalization=quantilization
  normalization: standardization
  n_quantiles: 5
  columns:
    - nb_non_classes
    - nb_sol
    - nb_vegetation_basse
    - nb_vegetation_moyenne
    - nb_vegetation_haute
    - nb_bati
    - nb_pont
    - nb_eau
    - nb_sursol_perenne

OutliersSampler:
  columns:
    - nb_non_classes
    - nb_sol
    - nb_vegetation_basse
    - nb_vegetation_moyenne
    - nb_vegetation_haute
    - nb_bati
    - nb_pont
    - nb_eau
    - nb_sursol_perenne
  hdbscan_kwargs:
    min_cluster_size: 50
    min_samples: 50
    cluster_selection_method: eom

TargettedSampler:

  # Critères de sélection des cibles suit le schéma :
  #   target_min_samples_proportion: float. Proportion minimale cible dans le jeu de données final.
  # Nota: minuscules attendues pour les noms de colonnes.
  targets:

    # Cibles obtenues par croisement avec des BD externes (BD Uni)
    # Cibles obtenues par croisement avec des BD externes (BD Uni)


    # specific Buildings 11 %
    nb_points_bati_heq_500:
      target_min_samples_proportion: 0.08    # 10% pour les bâti, dont 1% de serres et 1% de bâti industriel, + 8% bâti 
    presence_de_serres:
      target_min_samples_proportion: 0.01
    presence_de_bati_industriel_agricole_commercial:
      target_min_samples_proportion: 0.01
    presence_de_bati_sous_veget:
      target_min_samples_proportion: 0.01


    # BRIDGES 6 %
    nb_points_pont_heq_50:
      target_min_samples_proportion: 0.06


    # specific hydro 7 %
    nb_points_eau_heq_50:
      target_min_samples_proportion: 0.04   # 5% pour l'hydro, dont 1% d'intersection avec les surfaces d'eau BD Topo
    
    presence_de_surfaces_d_eau_et_eau:
      target_min_samples_proportion: 0.01

    points_eau_sans_sol: 
      target_min_samples_proportion: 0.01
    
    points_eau_et_sol_proche_niveau_mer: 
      target_min_samples_proportion: 0.01 


    # specific lasting_aboveground 8 %
    nb_points_sursol_perenne_heq_10:
      target_min_samples_proportion: 0.03    # 8% pour le sursol pérenne, dont 5% avec les croisements BD topo : permettent d'assurer une représentativité des différents types de sursol pérenne
    
    presence_de_pylone_et_sursolperenne:
      target_min_samples_proportion: 0.01

    presence_d_antenne_et_sursolperenne:
      target_min_samples_proportion: 0.01

    presence_d_eolienne_et_sursolperenne:
      target_min_samples_proportion: 0.01

    presence_sursolperenne_et_vegetation:
      target_min_samples_proportion: 0.01

    presence_de_catenaires_et_sursolperenne:
      target_min_samples_proportion: 0.01


    # specific unclassified ( trucks, on roads, parking, etc.) 5 %
    nb_points_non_classes_heq_50:
      target_min_samples_proportion: 0.03    # 5% pour le non classé, dont 2% visés par les parking/autoroutes


    # modifier par presence_camions
    presence_de_camions:
      target_min_samples_proportion: 0.01  # presence de camions explicite verifiee manuellement

    presence_parking_et_voitures:
      target_min_samples_proportion: 0.01   #  voiture : 8m² soit 250 points non classés


    # Custom 
    
    foret:
      target_min_samples_proportion: 0.05


    fort_devers_denivele_heq_45:
      target_min_samples_proportion: 0.02

    points_altitude_heq_2500m:
      target_min_samples_proportion: 0.04

    nb_points_bati_heq_quarter_of_all_points:
      target_min_samples_proportion: 0.05