# Configuration pour l'optimisation de l'échantillonnage de patches.

# Objectif de taille du dataset final.
target_total_num_patches: 5000  # 250km² = 100000 samples, 5000 samples -> 20x reduction  | Alternatively 75km² = 30000 samples.
frac_validation_set:  0.1 # float,ou "null" pour que la colonne "split" prenne la valeur "test" partout.

# kwargs for lipac database
connector_kwargs:
  gpd_database_path: "./outputs/samplings/LiPaCConnector-CopySampler/LiPaCConnector-CopySampler-train.gpkg"
  split: "any"

# LA SUITE ICI SUIT EXACTEMENT LA CONFIG POUR LIPAC
# TODO: utiliser hydra. Avoir une config par défaut orientée vers lipac. Avoir une config alternative pour les données synthétiques,
# et ce pour chaque connectoir/sampler. 


DiversitySampler:
  # Gestion par parties (chunk) des vignettes via FPS.
  # Les vignettes sont ordonnées par leur identifiant unique "patch_id", et l'id est supposé avoir été choisi incrémentalement
  # à mesure que la base LiPaC est peuplée. D'où un notion de diversité qui va être également spatialisée.
  max_chunk_size_for_fps: 20000
  # "standardization" or "quantilization"
  # n_quantiles is only used if normalization=quantilization
  normalization: standardization
  n_quantiles: 5
  columns:
    - nb_non_classes
    - nb_sol
    - nb_vegetation_basse
    - nb_vegetation_moyenne
    - nb_vegetation_haute
    - nb_bati
    - nb_pont
    - nb_eau
    - nb_sursol_perenne

OutliersSampler:
  columns:
    - nb_non_classes
    - nb_sol
    - nb_vegetation_basse
    - nb_vegetation_moyenne
    - nb_vegetation_haute
    - nb_bati
    - nb_pont
    - nb_eau
    - nb_sursol_perenne
  hdbscan_kwargs:
    min_cluster_size: 50
    min_samples: 50
    cluster_selection_method: eom

TargettedSampler:
  # nom_du_critère_pour_les_logs:
  #   target_min_samples_proportion: float. Proportion minimale cible dans le jeu de données final.
  # Nota: minuscules attendues pour les noms de colonnes.
  targets:

    # Cibles obtenues par croisement avec des BD externes (BD Uni)

    presence_de_pylones:
      target_min_samples_proportion: 0.02

    presence_de_surfaces_d_eau:
      target_min_samples_proportion: 0.02

    presence_d_autoroutes:
      target_min_samples_proportion: 0.02

    # Custom - Based on points

    nb_points_eau_heq_50:
      target_min_samples_proportion: 0.05

    nb_points_sursol_perenne_heq_50:
      target_min_samples_proportion: 0.05

    nb_points_pont_heq_50:
      target_min_samples_proportion: 0.05

    nb_points_bati_heq_500:
      target_min_samples_proportion: 0.15

    nb_points_bati_heq_quarter_of_all_points:
      target_min_samples_proportion: 0.05

    # Custom - others

    fort_devers_denivele_entre_30_45:
      target_min_samples_proportion: 0.04

    fort_devers_denivele_heq_45:
      target_min_samples_proportion: 0.04

    points_haute_altitude_entre_1000m_2000m:
      target_min_samples_proportion: 0.04

    points_haute_altitude_heq_2000m:
      target_min_samples_proportion: 0.04
