# Configuration pour l'optimisation de l'échantillonnage de patches.

# Objectif de taille du dataset final.
target_total_num_patches: 5000  # 250km² = 100000 samples, 5000 samples -> 20x reduction  | Alternatively 75km² = 30000 samples.
frac_validation_set:  0.1 # float or "null" for test set.

# kwargs for lipac database
connector_kwargs:
  credentials_file_path: "credentials.yml"
  db_lipac_host: "lidar-ia-vm3"
  db_lipac_name: "lidar_patch_catalogue"
  # extraction_sql_query -> croisement unique des tables de Lipac. Accès aux informations nécessaires.
  # Création a la volée des indicateurs booléens nécessaires à TargettedSampler.
  extraction_sql_query: >
    SELECT 
      id, geometrie, dalle_id, nb_points_total,
      nb_points_sol, nb_points_bati,
      nb_points_vegetation_basse,
      nb_points_vegetation_moyenne,
      nb_points_vegetation_haute, 
      nb_points_pont, 
      nb_points_eau,
      nb_points_sursol_perenne, 
      nb_points_non_classes,
      nb_points_artefacts,
      denivele, 
      altitude,
      (nb_points_bati >= 500) AS nb_points_bati_heq_500,
      ((nb_points_bati / nb_points_total) >= 0.5) AS nb_points_bati_heq_half_of_all_points,
      nb_points_eau >= 50 AS nb_points_eau_heq_50,
      nb_points_pont >= 50 AS nb_points_pont_heq_50,
      nb_points_sursol_perenne >= 50 AS nb_points_sursol_perenne_heq_500,
      (30 <= denivele) AND (denivele < 45) AS fort_devers_denivele_entre_30_45,
      45 <= denivele AS fort_devers_denivele_heq_45,
      (1000 <= altitude) AND (altitude < 2000) AS points_haute_altitude_entre_1000m_2000m,
      2000 <= altitude AS points_haute_altitude_heq_2000m,
      presence_de_surfaces_d_eau, 
      presence_de_pylones,
      presence_d_autoroutes
    FROM 
      vignette
    WHERE
      nb_points_total > 50

  max_chunksize_for_postgis_extraction: 100000

DiversitySampler:
  # Gestion par parties (chunk) des vignettes via FPS.
  # Les vignettes sont ordonnées par leur identifiant "id", et l'id est supposé avoir été choisi incrémentalement
  # à mesure que la base LiPaC est peuplée. D'où un notion de diversité qui va être également spatialisée.
  max_chunk_size_for_fps: 20000
  # standardization or quantilization
  normalization: quantilization
  # n_quantiles is only used if normalization=quantilization
  n_quantiles: 5
  columns:
    - nb_points_non_classes
    - nb_points_sol
    - nb_points_vegetation_basse
    - nb_points_vegetation_moyenne
    - nb_points_vegetation_haute
    - nb_points_bati
    - nb_points_pont
    - nb_points_eau
    - nb_points_sursol_perenne

OutliersSampler:
  columns:
    - nb_points_non_classes
    - nb_points_sol
    - nb_points_vegetation_basse
    - nb_points_vegetation_moyenne
    - nb_points_vegetation_haute
    - nb_points_bati
    - nb_points_pont
    - nb_points_eau
    - nb_points_sursol_perenne
  hdbscan_kwargs:
    min_cluster_size: 50
    min_samples: 50
    cluster_selection_method: eom

TargettedSampler:
  # nom_du_critère_pour_les_logs:
  #   target_min_samples_proportion: float. Proportion minimale cible dans le jeu de données final.
  targets:
    presence_de_pylones:
      target_min_samples_proportion: 0.02

    presence_de_surfaces_d_eau:
      target_min_samples_proportion: 0.02

    presence_d_autoroutes:
      target_min_samples_proportion: 0.02

    # Custom - Based on points

    nb_points_eau_heq_50:
      target_min_samples_proportion: 0.05

    nb_points_sursol_perenne_heq_500:
      target_min_samples_proportion: 0.05

    nb_points_pont_heq_50:
      target_min_samples_proportion: 0.05

    nb_points_bati_heq_500:
      target_min_samples_proportion: 0.15

    nb_points_bati_heq_half_of_all_points:
      target_min_samples_proportion: 0.05

    # Custom - others

    fort_devers_denivele_entre_30_45:
      target_min_samples_proportion: 0.04

    fort_devers_denivele_heq_45:
      target_min_samples_proportion: 0.04

    points_haute_altitude_entre_1000m_2000m:
      target_min_samples_proportion: 0.04

    points_haute_altitude_heq_2000m:
      target_min_samples_proportion: 0.04
