/*
Expected columns are (all caps):
- geometry: geometry of the patch
- patch_id: unique id of each patch in query result.
- file_id: unique id of each file in query result.
- file_path: path for data extraction, used after sampling.
*/
SELECT VIGNETTE_ET_CHEMIN.*,
	DALLE.RACINE_DU_NOM AS FILE_ID
FROM
	(SELECT DETAILED_VIGNETTES.*,
			FICHIER_LIDAR.CHEMIN_DALLES AS FILE_PATH
		FROM
			(SELECT VIGNETTE_REQUIS.*,
					NB_TOTAL,
					NB_SOL,
					NB_BATI,
					NB_VEGETATION_BASSE,
					NB_VEGETATION_MOYENNE,
					NB_VEGETATION_HAUTE,
					NB_PONT,
					NB_EAU,
					NB_SURSOL_PERENNE,
					NB_NON_CLASSES,
					NB_ARTEFACTS,
					DENIVELE,
					ALTITUDE,
					(NB_BATI >= 500) AS NB_BATI_HEQ_500,
					((NB_BATI / NB_TOTAL) >= 0.5) AS NB_POINTS_BATI_HEQ_HALF_OF_ALL_POINTS,
					NB_EAU >= 50 AS NB_POINTS_EAU_HEQ_50,
					NB_PONT >= 50 AS NB_POINTS_PONT_HEQ_50,
					NB_SURSOL_PERENNE >= 50 AS NB_POINTS_SURSOL_PERENNE_HEQ_500,
					((DENIVELE >= 30)
						AND (DENIVELE < 45)) AS FORT_DEVERS_DENIVELE_ENTRE_30_45,
					(DENIVELE >= 45) AS FORT_DEVERS_DENIVELE_HEQ_45,
					((1000 <= ALTITUDE)
						AND (ALTITUDE < 2000)) AS POINTS_HAUTE_ALTITUDE_ENTRE_1000M_2000M,
					2000 <= ALTITUDE AS POINTS_HAUTE_ALTITUDE_HEQ_2000M
				FROM
					(SELECT VIGNETTE.ID AS PATCH_ID,
							VIGNETTE.DALLE_ID,
							VIGNETTE.GEOMETRIE AS GEOMETRY
						FROM VIGNETTE) AS VIGNETTE_REQUIS
				JOIN STAT_VIGNETTE_LIDAR ON VIGNETTE_REQUIS.PATCH_ID = STAT_VIGNETTE_LIDAR.VIGNETTE_ID) AS DETAILED_VIGNETTES
		JOIN FICHIER_LIDAR ON DETAILED_VIGNETTES.DALLE_ID = FICHIER_LIDAR.DALLE_ID
		WHERE FICHIER_LIDAR.VERSION_DE_REFERENCE) AS VIGNETTE_ET_CHEMIN
JOIN DALLE ON VIGNETTE_ET_CHEMIN.DALLE_ID = DALLE.ID;