# Configuration pour l'optimisation de l'échantillonnage de patches.


# 75km² = 30k patches. 1% of 75km² = 300 patches.
target_total_num_patches: 50
# target_total_num_patches: 30000

frac_validation_set:  0.1 # float 

# Définition du jeu de données synthétique
connector_kwargs:
  # Lower
  # Création pour chaque prévalence d'un indicateur binaire C0, C1, etc.
  binary_descriptors_prevalence: [0.005, 0.005, 0.005, 0.7]
  db_size: 200
  split: "train"

  # 2500km²=4M patches
  # db_size: 4000000

TargettedSampler:
  targets:
    C0:
      target_min_samples_proportion: 0.20
    C1:
      target_min_samples_proportion: 0.05
    C2:
      target_min_samples_proportion: 0.05
    C3:
      target_min_samples_proportion: 0.2

DiversitySampler:
  max_chunk_size_for_fps: 5000
  # standardization or quantilization
  normalization: standardization
  # n_quantiles is only used if normalization=quantilization
  n_quantiles: 20 
  columns:
    - nb_non_classes
    - nb_sol
    - nb_vegetation_basse
    - nb_vegetation_moyenne
    - nb_vegetation_haute
    - nb_bati
    - nb_pont
    - nb_eau
    - nb_sursol_perenne

OutliersSampler:
  columns:
    - nb_non_classes
    - nb_sol
    - nb_vegetation_basse
    - nb_vegetation_moyenne
    - nb_vegetation_haute
    - nb_bati
    - nb_pont
    - nb_eau
    - nb_sursol_perenne
  hdbscan_kwargs:
    min_cluster_size: 50
    min_samples: 50
    cluster_selection_method: eom