# Configuration pour l'optimisation de l'échantillonnage de patches.
# Idées : liste de champs de la BD et des critères permettant de les requêter. Directement sous la forme SQL si plus simple :
# Nota: on pourra passer à un format csv si plus simple à inspecter / manipuler, mais attention à la forme des requêtes sql!

# TODO: make a parser for the config once it is more stable. Check for constraints in range [0-1] and if their sum is <100%.

num_tiles_in_sampled_dataset: 10
frac_test_set:  0.1 # float 
use_spatial_sampling: true

# 75km² = 30k tiles. 1% of 75km² = 300 tiles.
# num_tiles_in_sampled_dataset: 30000

criteria:
  C0:
    target_min_samples_proportion: 0.01
  C1:
    target_min_samples_proportion: 0.05
  C2:
    target_min_samples_proportion: 0.05
  # Order of criteria has no impact: they are sorted in code by target.
  C4:
    target_min_samples_proportion: 0.2
  C3:
    target_min_samples_proportion: 0.99
  C3C4:
    where: "(C3 > 0) & (C4 > 0)"
    target_min_samples_proportion: 0.1



# kwargs for synthetic connector
connector_kwargs:
  # Lower
  binary_descriptors_prevalence: [0.005, 0.005, 0.005, 0.7, 0.7]
  db_size: 10000

  # 2500km²=4M tiles
  # db_size: 4000000