# Configuration pour l'optimisation de l'échantillonnage de patches.


# 75km² = 30k tiles. 1% of 75km² = 300 tiles.
target_total_num_tiles: 500
# target_total_num_tiles: 30000

frac_validation_set:  0.0 # float 

# Définition du jeu de données synthétique
connector_kwargs:
  # Lower
  # Création pour chaque prévalence d'un indicateur binaire C0, C1, etc.
  binary_descriptors_prevalence: [0.005, 0.005, 0.005, 0.7]
  db_size: 10000

  # 2500km²=4M tiles
  # db_size: 4000000

TargettedSampler:
  targets:
    C0:
      target_min_samples_proportion: 0.01
    C1:
      target_min_samples_proportion: 0.05
    C2:
      target_min_samples_proportion: 0.05
    C3:
      target_min_samples_proportion: 0.2

DiversitySampler:
  max_chunk_size_for_fps: 5000
  # standardization or quantilization
  normalization: standardization
  # n_quantiles is only used if normalization=quantilization
  n_quantiles: 20 
  columns:
    - nb_points_non_classes
    - nb_points_sol
    - nb_points_vegetation_basse
    - nb_points_vegetation_moyenne
    - nb_points_vegetation_haute
    - nb_points_bati
    - nb_points_pont
    - nb_points_eau
    - nb_points_sursol_perenne


