# Configuration pour l'optimisation de l'échantillonnage de patches.


# 75km² = 30k tiles. 1% of 75km² = 300 tiles.
num_tiles_in_sampled_dataset: 500
# num_tiles_in_sampled_dataset: 30000

frac_validation_set:  0.0 # float 

# Définition du jeu de données synthétique
connector_kwargs:
  # Lower
  # Création pour chaque prévalence d'un indicateur binaire C0, C1, etc.
  binary_descriptors_prevalence: [0.005, 0.005, 0.005, 0.7, 0.7]
  db_size: 10000

  # 2500km²=4M tiles
  # db_size: 4000000

targets_for_TargettedSampler:
  C0:
    where: "C0 > 0"
    target_min_samples_proportion: 0.01
  C1:
    where: "C1 > 0"
    target_min_samples_proportion: 0.05
  C2:
    where: "C2 > C1"
    target_min_samples_proportion: 0.05
  C3:
    where: "C3 > 0"
    target_min_samples_proportion: 0.2
  C2_et_C3_sup_a_zero:
    where: "(C2 > 0) & (C3 > 0)"
    target_min_samples_proportion: 0.1

DiversitySampler:
  max_chunk_size_for_fps: 5000
  # standardization or quantilization
  normalization: standardization
  # n_quantiles is only used if normalization=quantilization
  n_quantiles: 20 
  columns:
    - nb_points_non_classes
    - nb_points_sol
    - nb_points_vegetation_basse
    - nb_points_vegetation_moyenne
    - nb_points_vegetation_haute
    - nb_points_bati
    - nb_points_pont
    - nb_points_eau
    - nb_points_sursol_perenne


