name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA
        echo $CONDA/bin >> $GITHUB_PATH
      shell: bash

    - name: Cache Conda environment
      uses: actions/cache@v3
      with:
        path: |
          $CONDA
          $CONDA/envs
          $CONDA/bin
        key: conda-${{ hashFiles('environment.yml') }}
      id: conda_cache

    - name: Install dependencies (if no cached conda envs were found)
      if: steps.conda_cache.outputs.cache-hit != 'true'
      run: |
        conda install mamba -n base -c conda-forge --yes
        mamba env update --file environment.yml --name base

    - name: Lint with flake8
      run: |
        mamba install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=144 --statistics

    - name: Test with pytest
      run: |
        # Run tests using a special makefile target that multithread them.
        make tests
